# Generated by Django 3.1.6 on 2021-02-12 13:24
import json
from django.db import migrations, models
from django.conf import settings


def seed_cities(apps, schema_editor):
    """Seed citiy data"""
    City = apps.get_model("locations", "City")

    seed_dir = settings.CITIES_DIR

    with open(seed_dir + '/data.txt') as json_file:
        data = json.load(json_file)

        for i in data:
            city = City(name=i['name'], country=i['country'])
            city.save()

def reverse_func(apps, schema_editor):
    City = apps.get_model("locations", "City")

    City.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_cities, reverse_func)
    ]
